---
title: "processR"
author: "Matthew Supernaw"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Simple Example


```{r, echo=TRUE, results='asis'}
library(processR)
library(Rcpp)
library(RInside)

#get the Rcpp module
p <- Rcpp::Module(module = "processR", PACKAGE = "processR")

v <- 10

test <- function() {
  #declare a list globally
  results<<-list()
  
  for (i in 1:2) {
    #modify a global variable
    v <- v + 1
    #multiply i by the processR.rank
    results[[i]]<<-i * processR.rank
  }
  
  for (i in 1:2) {
    #print to standard out (to be captured after completion)
    print(paste("rank", paste(processR.rank, " -> hi from the test function")))
  }
  
}

#create a pool children
pool <- list()

#fill the pool with children
for (i in 1:processR::HardwareConcurrency()) {
  
  #creat a new child
  pool[[i]] <- new(p$Process)
  
  #pass the entry function, environment, and child rank
  pool[[i]]$start(test, environment(), i)
}


print("waiting...")
for (j in 1:length(pool)) {
  
  #wait for the children to finish
  pool[[j]]$wait()
  
  #print the child output stream
  pool[[j]]$print()
  cat("\n");
  
  #get the child's environment
  env<-pool[[j]]$get_environment()
  
  #access the global "results" list created by the test function
  str <- paste0(unlist(env[["results"]]), collapse = "\n")
  cat(str)
  cat("\n");
}

print("done.")


```


