# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

copyEnvironment <- function(sourceEnv) {
    .Call(`_processR_copyEnvironment`, sourceEnv)
}

RunProcess <- function(fun, env) {
    invisible(.Call(`_processR_RunProcess`, fun, env))
}

CreateProcess <- function() {
    .Call(`_processR_CreateProcess`)
}

CreateProcessPool <- function(size) {
    .Call(`_processR_CreateProcessPool`, size)
}

