# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

copyEnvironment <- function(sourceEnv) {
    .Call(`_processR_copyEnvironment`, sourceEnv)
}

writeToSharedMemory <- function(shared_memory_name, serialized_env) {
    invisible(.Call(`_processR_writeToSharedMemory`, shared_memory_name, serialized_env))
}

readEnvironmentFromSharedMemory <- function(shared_memory_name) {
    .Call(`_processR_readEnvironmentFromSharedMemory`, shared_memory_name)
}

CreateSharedEnvironment <- function(name) {
    .Call(`_processR_CreateSharedEnvironment`, name)
}

CreateSharedEnvironmentNoReturn <- function(name) {
    invisible(.Call(`_processR_CreateSharedEnvironmentNoReturn`, name))
}

readSharedEnvironment <- function(name) {
    .Call(`_processR_readSharedEnvironment`, name)
}

RunProcess <- function(fun, env) {
    invisible(.Call(`_processR_RunProcess`, fun, env))
}

RunChild <- function(fun, env) {
    invisible(.Call(`_processR_RunChild`, fun, env))
}

CallRProcess <- function(fun, env) {
    .Call(`_processR_CallRProcess`, fun, env)
}

HardwareConcurrency <- function() {
    .Call(`_processR_HardwareConcurrency`)
}

CreateProcessPool <- function(size) {
    .Call(`_processR_CreateProcessPool`, size)
}

