# Run r cmd check
name: call-r-cmd-check
- name: Install boost
  uses: MarkusJx/install-boost@v2.4.4
  id: install-boost
  with:
      # REQUIRED: Specify the required boost version
      # A list of supported versions can be found here:
      # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
      boost_version: 1.73.0
      # OPTIONAL: Specify a custon install location
      boost_install_dir: C:\some_directory
      # OPTIONAL: Specify a platform version
      platform_version: 2019
      # OPTIONAL: Specify a toolset
      toolset: msvc
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
# The default build trigger is to run the action on every push and pull request, for any branch
  push:
  # To run the default repository branch weekly on sunday, uncomment the following 2 lines
  #schedule:
    #- cron: '0 0 * * 0'
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
    with: 
      gha_timeout_minutes: 60
